/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type HexColor = string;

export interface ColorPalletSchema {
  $schema: string;
  interface: {
    primary: Normal;
    secondary: Normal;
    tertiary: Normal;
    error: Normal;
    warning: Normal;
    neutral: Full;
    neutralVariant: Normal;
  };
  syntax: {
    name: string;
    tones: Normal;
  }[];
  ansi: {
    black: Terminal;
    brightBlack: Terminal;
    red: Terminal;
    brightRed: Terminal;
    green: Terminal;
    brightGreen: Terminal;
    yellow: Terminal;
    brightYellow: Terminal;
    blue: Terminal;
    brightBlue: Terminal;
    magenta: Terminal;
    brightMagenta: Terminal;
    cyan: Terminal;
    brightCyan: Terminal;
    white: Terminal;
    brightWhite: Terminal;
    orange: Terminal;
    brightOrange: Terminal;
  };
}
export interface Normal {
  base?: HexColor;
  _0: HexColor;
  _5: HexColor;
  _10: HexColor;
  _15: HexColor;
  _20: HexColor;
  _25: HexColor;
  _30: HexColor;
  _35: HexColor;
  _40: HexColor;
  _50: HexColor;
  _60: HexColor;
  _70: HexColor;
  _80: HexColor;
  _90: HexColor;
  _95: HexColor;
  _98: HexColor;
  _99: HexColor;
  _100: HexColor;
}
interface Full {
  _0: HexColor;
  _4: HexColor;
  _6: HexColor;
  _10: HexColor;
  _12: HexColor;
  _17: HexColor;
  _20: HexColor;
  _22: HexColor;
  _24: HexColor;
  _30: HexColor;
  _40: HexColor;
  _50: HexColor;
  _60: HexColor;
  _70: HexColor;
  _80: HexColor;
  _87: HexColor;
  _90: HexColor;
  _92: HexColor;
  _94: HexColor;
  _95: HexColor;
  _96: HexColor;
  _98: HexColor;
  _99: HexColor;
  _100: HexColor;
}
interface Terminal {
  base: HexColor;
  _0: HexColor;
  _5: HexColor;
  _10: HexColor;
  _15: HexColor;
  _20: HexColor;
  _25: HexColor;
  _30: HexColor;
  _35: HexColor;
  _40: HexColor;
  _50: HexColor;
  _60: HexColor;
  _70: HexColor;
  _80: HexColor;
  _90: HexColor;
  _95: HexColor;
  _98: HexColor;
  _99: HexColor;
  _100: HexColor;
  [k: string]: unknown;
}
